### ISSUE TITLE
Can close ARGoS GUI, but can not quit ARGoS in terminal

### ISSUE THREAD

**Issue by lukey11-zz** [BCLab-UNM/iAnt-ARGoS#12]
Hi all,

I am running ARGoS in Ubuntu. I can close ARGoS GUI when the experiment is finished. However, it does not quit in the terminal. I have to force the program to quit every time. This was not the problem in MAC.  

![screenshot from 2015-07-02 10 21 12](https://cloud.githubusercontent.com/assets/7494418/8482043/2cc2e444-20a4-11e5-9695-38619906b355.png)

**Comment by Linh-Tran** [comment]
That's odd. I don't know what will fix that. I also encountered an issue with running it multiple times on Mac. It won't update or generate a new iAntTagData.txt when it is finished compiling.

**Comment by lukey11-zz** [comment]
Actually, it will quite in the terminal, but you need to wait for 3 mins after your close the GUI of ARGoS.

**Comment by lukey11-zz** [comment]
Hi Linh,

Your problem is the setting of the output parameter. You need to set the parameter OutputData=1 in the XML file.
