### ISSUE TITLE
Issue generating and updating iAntTagData.txt file.

### ISSUE THREAD

**Issue by Linh-Tran** [BCLab-UNM/iAnt-ARGoS#13]
The new development ARGoS code won't update or generate a new  iAntTagData.txt with multiple runs using mac. I think the issues is in the iAnt_loop_function.cpp where iAntTagData.txt is being created. I will try to compare it with ARGoS-master to figure out the problem in the meantime.

**Comment by lukey11-zz** [comment]
Hi Linh,
You need to set the parameter OutputData=1 in the XML file. Then, it will generate the output file iAntTagData.txt.
