### ISSUE TITLE
Error in Qt_user_function. 

### ISSUE THREAD

**Issue by safeeulbashir** [BCLab-UNM/iAnt-ARGoS#2]
Amritansh is having problem with running the argos with the code that is
in github.  I tried to run the "make" command from his account in the CS
machine. But it is generating some errors with the opengl files. But it is
running in my CS account without any error. The error log is attached.
Please have a look.

[ 25%] Built target iAnt_pheromone
[ 50%] Built target iAnt_controller
[ 75%] Building CXX object loop_functions/CMakeFiles/iAnt_loop_functions.dir/iAnt_qt_user_functions.cpp.o
In file included from /usr/include/argos3/plugins/simulator/visualizations/qt-opengl/qtopengl_widget.h:26:0,
                 from /usr/include/argos3/plugins/simulator/visualizations/qt-opengl/qtopengl_user_functions.h:17,
                 from /nfs/student/a/amritansh/Downloads/iAnt-ARGoS-master/loop_functions/iAnt_qt_user_functions.h:6,
                 from /nfs/student/a/amritansh/Downloads/iAnt-ARGoS-master/loop_functions/iAnt_qt_user_functions.cpp:1:
/usr/include/argos3/plugins/simulator/visualizations/qt-opengl/qtopengl_camera.h:16:19: fatal error: QObject: No such file or directory
compilation terminated.
make[2]: **\* [loop_functions/CMakeFiles/iAnt_loop_functions.dir/iAnt_qt_user_functions.cpp.o] Error 1
make[1]: **\* [loop_functions/CMakeFiles/iAnt_loop_functions.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Antonio-Griego** [comment]
This is a perplexing error. Unfortunately, considering that it works on your machine and not his the only thing I could suggest try is to  the following:

Delete the contents of the BUILD folder and run cmake and make again from the beginning per the instructions on the wiki page and README.md

If this does not work, it may indicate problems with file/folder permissions on the account in question.

--Antonio

**Comment by safeeulbashir** [comment]
I tried to delete all the files and rebuild it. But its not working.

**Comment by Antonio-Griego** [comment]
Closing this issue for now since it is from a now completed class. Will reopen if students continue to have this error in the future.
