### ISSUE TITLE
Description: Error Document Empty

### ISSUE THREAD

**Issue by safeeulbashir** [BCLab-UNM/iAnt-ARGoS#4]
Issue came from one of the student.
Hi guys,

I'm writing XML files in python for each run of iAnt, but it seems that no
matter what i do ARGoS sends back

Couldn't load experiments/765PEGRKCF0.argos ticpp.cpp@823
Description: Failed to open file

765PEGRKCF0.argos being the name for the xml file. I've checked the
permissions and everything should be ok. This is the file I'm writing and
as far as I've checked its writing all the attributes correctly, but the
only difference is the formatting. Any ideas?

To analyze the issue I have created a blank xml file. And copied the text
from your configuration file. It is running successfully. I don't know whether it is an issue with argos or with his code.
![screenshot from 2015-04-21 11 44 54](https://cloud.githubusercontent.com/assets/6511438/7258842/403472b0-e81c-11e4-896e-383998cf8c92.png)

**Comment by safeeulbashir** [comment]
Since I can add the file over here, Let me know if you need the configuration file.

**Comment by Antonio-Griego** [comment]
ARGoS can be incredibly picky about how the XML file is formatted. Is there any way I could take a look at the XML file that is causing this particular error?

--Antonio
